package com.horvat.gui.dialogs;

import com.horvat.dl.entities.IDisplayable;
import com.horvat.gui.dialogs.optionDialogs.base.OptionDialog;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.print.PrinterException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class DisplayDataDialog extends OptionDialog<Object> {
    private JPanel contentPane;
    private JTable table;

    public DisplayDataDialog(Window owner, String title, int width, int height) {
        super(owner, title, width, height);
        setContentPane(contentPane);
    }

    public DisplayDataDialog(Window owner, String title, int width, int height, List<? extends IDisplayable> data) {
        this(owner, title, width, height);
        setTableData(data);
    }

    public void setTableData(List<? extends IDisplayable> data) {
        if (data.size() == 0)
            return;

        List<String> columnNames = new ArrayList<>();
        Object[][] modelData = new Object[data.size()][];

        for (int i = 0; i < data.size(); i++) {
            IDisplayable displayable = data.get(i);
            Map<String, Map<String, Object>> displayDataGroups = displayable.getDisplayDataGroups();

            List<Object> modelObjects = new ArrayList<>();

            for (String key : displayDataGroups.keySet()) {
                Map<String, Object> displayData = displayDataGroups.get(key);

                if (key.equals(IDisplayable.NON_GROUPED_NAME)) {
                    for (String columnName : displayData.keySet()) {
                        if (!columnNames.contains(columnName))
                            columnNames.add(columnName);

                        modelObjects.add(displayData.get(columnName));
                    }
                } else {
                    if (!columnNames.contains(key))
                        columnNames.add(key);

                    modelObjects.add("Link button for " + key);
                }
            }

            modelData[i] = modelObjects.toArray();
        }

        table.setModel(new DefaultTableModel(modelData, columnNames.toArray()));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setHorizontalScrollBarPolicy(31);
        contentPane.add(scrollPane1, BorderLayout.CENTER);
        table = new JTable();
        table.setAutoResizeMode(4);
        scrollPane1.setViewportView(table);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
