package com.horvat.gui.app;

import com.horvat.bll.viewmodels.MainMenuViewModel;
import com.horvat.bll.viewmodels.doctor.DoctorMenuViewModel;
import com.horvat.bll.viewmodels.receptionist.ReceptionistMenuViewModel;
import com.horvat.dl.entities.Doctor;
import com.horvat.gui.dialogs.doctor.DoctorMenuDialog;
import com.horvat.gui.dialogs.option.ChooseDoctorDialog;
import com.horvat.gui.dialogs.receptionist.ReceptionistMenuDialog;
import com.horvat.gui.dialogs.report.ReportMenuDialog;

import javax.swing.*;
import java.awt.*;

public class MainMenuWindow extends JFrame {
    private JButton btnDoctorLogin;
    private JPanel contentPane;
    private JButton btnReceptionistLogin;
    private JButton btnReports;

    private MainMenuViewModel viewModel;

    public MainMenuWindow(String title, int width, int height, MainMenuViewModel viewModel) throws HeadlessException {
        super(title);
        setSize(width, height);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        this.viewModel = viewModel;
        setContentPane(contentPane);

        btnDoctorLogin.addActionListener(e -> onDoctorLogin());

        btnReceptionistLogin.addActionListener(e -> onReceptionistLogin());

        btnReports.addActionListener(e -> onReportRequest());
    }

    private void onReportRequest() {
        ReportMenuDialog reportDialog = new ReportMenuDialog(
                this, "Report menu", 400, 600
        );

        setVisible(false);
        reportDialog.showDialog();
        setVisible(true);
    }

    private void onReceptionistLogin() {
        ReceptionistMenuDialog receptionistMenuDialog = new ReceptionistMenuDialog(
                this, "Receptionist menu", 400, 600,
                new ReceptionistMenuViewModel()
        );

        setVisible(false);
        receptionistMenuDialog.showDialog();
        setVisible(true);
    }

    private void onDoctorLogin() {
        java.util.List<Doctor> doctors = viewModel.getDoctors();

        ChooseDoctorDialog chooseDoctorDialog = new ChooseDoctorDialog(this, "Choose doctor", doctors);
        setVisible(false);
        Doctor chosenDoctor = chooseDoctorDialog.showDialog();

        if (chosenDoctor != null) {
            DoctorMenuDialog doctorMenuDialog = new DoctorMenuDialog(
                    this, "Doctor Menu", 400, 600,
                    new DoctorMenuViewModel(chosenDoctor)
            );
            doctorMenuDialog.showDialog();
        }

        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridBagLayout());
        btnDoctorLogin = new JButton();
        btnDoctorLogin.setText("Login as a doctor");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        contentPane.add(btnDoctorLogin, gbc);
        btnReceptionistLogin = new JButton();
        btnReceptionistLogin.setText("Login as a receptionist");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        contentPane.add(btnReceptionistLogin, gbc);
        btnReports = new JButton();
        btnReports.setText("View reports");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        contentPane.add(btnReports, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
