package com.horvat.gui.dialogs.doctor;

import com.horvat.bll.viewmodels.doctor.DoctorMenuViewModel;
import com.horvat.gui.dialogs.DisplayDataDialog;
import com.horvat.gui.dialogs.base.BaseDialog;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class DoctorMenuDialog extends BaseDialog<Object, DoctorMenuViewModel> {
    private JPanel contentPane;
    private JButton btnViewPatientsData;
    private JButton btnOrderTest;
    private JButton btnPrescribeMedicine;
    private JButton btnAlterData;

    public DoctorMenuDialog(Window owner, String title, int width, int height, DoctorMenuViewModel viewModel) {
        super(owner, title, width, height, viewModel);

        setContentPane(contentPane);
        initListeners();
    }

    private void initListeners() {
        // call onCancel() when cross is clicked
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                onCancel();
            }
        });

        // call onCancel() on ESCAPE
        contentPane.registerKeyboardAction(
                e -> onCancel(),
                KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
                JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
        );

        btnViewPatientsData.addActionListener(e -> {
            DisplayDataDialog displayDataDialog = new DisplayDataDialog(this, "Patient data", 1024, 768, viewModel.getPatients());
            displayDataDialog.showDialog();
        });
//
//        btnOrderTest.addActionListener(e -> {
//
//        });
//
//        btnPrescribeMedicine.addActionListener(e -> {
//
//        });
//
//        btnAlterData.addActionListener(e -> {
//
//        });
    }

    private void onOK() {
        close();
    }

    private void onCancel() {
        close();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 1, new Insets(10, 10, 10, 10), -1, -1));
        btnViewPatientsData = new JButton();
        btnViewPatientsData.setText("View patients' data");
        contentPane.add(btnViewPatientsData, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnOrderTest = new JButton();
        btnOrderTest.setText("Order test for a patient");
        contentPane.add(btnOrderTest, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnPrescribeMedicine = new JButton();
        btnPrescribeMedicine.setText("Prescribe medicine to patient");
        contentPane.add(btnPrescribeMedicine, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnAlterData = new JButton();
        btnAlterData.setText("Alter future tests / appointments");
        contentPane.add(btnAlterData, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
