package com.horvat.gui.dialogs.report;

import com.horvat.bll.viewmodels.report.DailyReportViewModel;
import com.horvat.bll.viewmodels.report.ReportMenuViewModel;
import com.horvat.bll.viewmodels.report.WeeklyOrMonthlyReportViewModel;
import com.horvat.gui.dialogs.base.CustomDialog;
import com.horvat.gui.dialogs.base.VMDialog;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class ReportMenuDialog extends VMDialog<ReportMenuViewModel> {
    private JPanel contentPane;
    private JButton btnDailyReport;
    private JButton btnWeeklyReport;
    private JButton btnMonthlyReport;

    public ReportMenuDialog(Window owner, String title, int width, int height, ReportMenuViewModel viewModel) {
        super(owner, title, width, height, viewModel);
        setContentPane(contentPane);

        initListeners();
    }

    private void initListeners() {
        btnDailyReport.addActionListener(e -> {
            DailyReportDialog dailyReportDialog = new DailyReportDialog(
                    this, "Daily report", 400, 400,
                    new DailyReportViewModel()
            );
            dailyReportDialog.showDialog();
        });

        btnWeeklyReport.addActionListener(e -> {
            WeeklyOrMonthlyReportDialog weeklyReportDialog = new WeeklyOrMonthlyReportDialog(
                    this, "Weekly report", 400, 400,
                    new WeeklyOrMonthlyReportViewModel(false)
            );
            weeklyReportDialog.showDialog();
        });

        btnMonthlyReport.addActionListener(e -> {
            WeeklyOrMonthlyReportDialog monthlyReportDialog = new WeeklyOrMonthlyReportDialog(
                    this, "Monthly report", 400, 400,
                    new WeeklyOrMonthlyReportViewModel(true)
            );
            monthlyReportDialog.showDialog();
        });

        // call onCancel() when cross is clicked
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                onCancel();
            }
        });

        // call onCancel() on ESCAPE
        contentPane.registerKeyboardAction(e -> onCancel(), KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
    }

    private void onOK() {
        close();
    }

    private void onCancel() {
        close();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        btnDailyReport = new JButton();
        btnDailyReport.setText("Daily report");
        panel1.add(btnDailyReport, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnWeeklyReport = new JButton();
        btnWeeklyReport.setText("Weekly report");
        panel1.add(btnWeeklyReport, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnMonthlyReport = new JButton();
        btnMonthlyReport.setText("Monthly report");
        panel1.add(btnMonthlyReport, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
